const defaultContent = {
  brandNameAr:'باسم عبدالغفور', brandNameEn:'Basem Alshameri',
  eyebrowAr:'مدير عمليات | مشتريات ولوجستيات | تجارة إلكترونية', eyebrowEn:'Operations Manager | Purchasing & Logistics | E-commerce',
  heroNameAr:'باسم عبدالغفور عبدالقوي أحمد', heroNameEn:'Basem Abdulghafoor Abdulqawi Ahmed',
  heroTextAr:'مدير عمليات بخبرة تتجاوز 15 عاماً في إدارة العمليات التشغيلية، المشتريات الدولية، الخدمات اللوجستية، سلاسل الإمداد، إدارة البيانات، والتجارة الإلكترونية.', heroTextEn:'Operations Manager with 15+ years of experience across operational management, international purchasing, logistics, supply chain, data management, and e-commerce.',
  locationAr:'الدمام، المملكة العربية السعودية', locationEn:'Dammam, Saudi Arabia',
  profileTextAr:'جاهز للتعاون في تطوير العمليات، التجارة الإلكترونية، المشتريات، واللوجستيات.', profileTextEn:'Available for collaboration in operations, e-commerce, purchasing, and logistics.',
  aboutAr:'أمتلك خبرة قوية في تحسين العمليات التشغيلية، إدارة الموردين، تنسيق الشحن والاستيراد، تطوير الاستراتيجيات الرقمية، وتحليل مؤشرات الأداء. أركز على تحويل الأهداف التشغيلية إلى إجراءات عملية قابلة للقياس والتحسين.', aboutEn:'I specialize in optimizing operational processes, vendor management, shipping and import coordination, digital strategy development, and performance indicator analysis. My focus is converting operational goals into measurable and improvable execution plans.',
  email:'basemalshameri6@gmail.com', linkedin:'https://linkedin.com/in/basem-al-shameri-b1a848395', cvAr:'assets/docs/cv-ar.pdf', cvEn:'assets/docs/cv-en.pdf'
};
const defaultVisibility={about:true,experience:true,education:true,certificates:true,contact:true};
const defaultSections=[];
const defaultCertificates=[];for(let i=1;i<=60;i++){defaultCertificates.push([`cert-${String(i).padStart(2,'0')}.jpg`, i<5?'academic':(i<17?'experience':'professional'), `شهادة رقم ${i}`, `Certificate ${i}`]);}
function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
let content={...defaultContent,...readJSON('portfolioContent',{})};
let visibility={...defaultVisibility,...readJSON('portfolioVisibility',{})};
let sections=readJSON('portfolioSections',defaultSections);
let certificates=readJSON('portfolioCertificates',defaultCertificates);
function fillContent(){document.querySelectorAll('[data-field]').forEach(el=>el.value=content[el.dataset.field]||'');document.querySelectorAll('[data-section-visible]').forEach(el=>el.checked=visibility[el.dataset.sectionVisible]!==false)}
function collectContent(){document.querySelectorAll('[data-field]').forEach(el=>content[el.dataset.field]=el.value.trim());document.querySelectorAll('[data-section-visible]').forEach(el=>visibility[el.dataset.sectionVisible]=el.checked)}
function esc(s=''){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function certRow(c=['cert-01.jpg','professional','عنوان الشهادة','Certificate title']){const div=document.createElement('div');div.className='cert-row';div.innerHTML=`<label>الصورة<input value="${esc(c[0]||'')}" data-cert="file"></label><label>التصنيف<select data-cert="cat"><option value="academic">أكاديمية</option><option value="professional">مهنية</option><option value="experience">خبرة</option></select></label><label>العنوان عربي<input value="${esc(c[2]||'')}" data-cert="ar"></label><label>العنوان إنجليزي<input value="${esc(c[3]||'')}" data-cert="en"></label><button class="remove-cert" type="button">حذف</button>`;div.querySelector('select').value=c[1]||'professional';div.querySelector('.remove-cert').onclick=()=>div.remove();return div}
function renderCerts(){const box=document.getElementById('certEditor');box.innerHTML='';certificates.forEach(c=>box.appendChild(certRow(c)))}
function collectCerts(){return [...document.querySelectorAll('.cert-row')].map(r=>[r.querySelector('[data-cert="file"]').value.trim(),r.querySelector('[data-cert="cat"]').value,r.querySelector('[data-cert="ar"]').value.trim(),r.querySelector('[data-cert="en"]').value.trim()]).filter(c=>c[0])}
function sectionRow(s={titleAr:'قسم جديد',titleEn:'New Section',bodyAr:'اكتب محتوى القسم هنا.',bodyEn:'Write section content here.',visible:true}){const div=document.createElement('div');div.className='custom-section-row';div.innerHTML=`<div class="row-head"><label><input type="checkbox" data-sec="visible" ${s.visible!==false?'checked':''}> إظهار القسم</label><button class="remove-cert" type="button">حذف القسم</button></div><div class="form-grid"><label>عنوان القسم عربي<input data-sec="titleAr" value="${esc(s.titleAr||'')}"></label><label>عنوان القسم إنجليزي<input data-sec="titleEn" value="${esc(s.titleEn||'')}"></label><label class="full">محتوى القسم عربي<textarea data-sec="bodyAr">${esc(s.bodyAr||'')}</textarea></label><label class="full">محتوى القسم إنجليزي<textarea data-sec="bodyEn">${esc(s.bodyEn||'')}</textarea></label></div>`;div.querySelector('.remove-cert').onclick=()=>div.remove();return div}
function renderSections(){const box=document.getElementById('sectionEditor');box.innerHTML='';sections.forEach(s=>box.appendChild(sectionRow(s)))}
function collectSections(){return [...document.querySelectorAll('.custom-section-row')].map(r=>({visible:r.querySelector('[data-sec="visible"]').checked,titleAr:r.querySelector('[data-sec="titleAr"]').value.trim(),titleEn:r.querySelector('[data-sec="titleEn"]').value.trim(),bodyAr:r.querySelector('[data-sec="bodyAr"]').value.trim(),bodyEn:r.querySelector('[data-sec="bodyEn"]').value.trim()})).filter(s=>s.titleAr||s.titleEn||s.bodyAr||s.bodyEn)}
function saveAll(){collectContent();certificates=collectCerts();sections=collectSections();localStorage.setItem('portfolioContent',JSON.stringify(content));localStorage.setItem('portfolioCertificates',JSON.stringify(certificates));localStorage.setItem('portfolioVisibility',JSON.stringify(visibility));localStorage.setItem('portfolioSections',JSON.stringify(sections));alert('تم حفظ كل التعديلات بنجاح')}
document.getElementById('saveAll').onclick=saveAll;
document.getElementById('addCert').onclick=()=>document.getElementById('certEditor').prepend(certRow());
document.getElementById('addSection').onclick=()=>document.getElementById('sectionEditor').prepend(sectionRow());
document.getElementById('resetData').onclick=()=>{if(confirm('هل تريد حذف جميع التعديلات والرجوع للنسخة الافتراضية؟')){['portfolioContent','portfolioCertificates','portfolioVisibility','portfolioSections'].forEach(k=>localStorage.removeItem(k));location.reload()}};
document.getElementById('exportData').onclick=()=>{collectContent();const data={portfolioContent:content,portfolioVisibility:visibility,portfolioSections:collectSections(),portfolioCertificates:collectCerts()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='portfolio-dashboard-data.json';a.click();URL.revokeObjectURL(a.href)};
fillContent();renderSections();renderCerts();
